#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only
#
# Git source code verification script
# https://github.com/pcmoore/git-verification_scripts
# Paul Moore <paul@paul-moore.com>
#

# NOTE: comments starting with '#@ ' will become info text in pstg
#@             Examines the coding style/format using astyle

# TODO: provide some config knob/arg for selecting dirs

####
# config

# support "**" in pathnames
shopt -s globstar

#
# allow list of build directories
#   format: space delimited file list
#
PATHS_ALLOWED=" **/*.c"

####
# functions

function git_uncommitted() {
	local changes=$(git status --porcelain 2>/dev/null | wc -l)
	[[ $changes -eq 0 ]] && return 1
	return 0
}

function tool_astyle() {
	# https://astyle.sourceforge.net
	astyle --options=none --lineend=linux --mode=c \
		--style=linux \
		--indent=force-tab=8 \
		--indent-col1-comments \
		--min-conditional-indent=0 \
		--max-continuation-indent=80 \
		--pad-oper \
		--align-pointer=name \
		--align-reference=name \
		--max-code-length=80 \
		--break-after-logical
}

function check_file() {
	[[ -z "$1" || ! -r "$1" ]] && return
	cat "$1" | tool_astyle | diff --color=auto -pu \
		--label="$1.orig" "$1" --label="$1" -
}

####
# main

# check for uncommitted changes
git_uncommitted && echo ">>> WARNING: you have uncommitted changes"

# loop through the files
rc=0
for i in $(git diff-tree --no-commit-id --name-only -r HEAD | sort -u); do
	for j in $PATHS_ALLOWED; do
		if [[ $i == ${j}* && $i =~ \.(c|h)$ ]]; then
			echo ">>> style differences in $i"
			check_file "$i"
			rc_tmp=$?
			[[ $rc -eq 0 ]] && rc=$rc_tmp
		fi
	done
done

exit $rc
