#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only
#
# Git source code verification script
# https://github.com/pcmoore/git-verification_scripts
# Paul Moore <paul@paul-moore.com>
#

# NOTE: comments starting with '#@ ' will become info text in pstg
#@             Runs the Linux Kernel's checkpatch.pl script

####
# config

# N/A

####
# functions

function exit_error() {
	echo ">>> error: $*"
	exit 1
}

function dep_check() {
	for i in $*; do
		command -v $i > /dev/null || exit_error "$i command not found"
	done
}

function kernel_top() {
	local top=$(pwd)
	while [[ ! -e $top/MAINTAINERS ]]; do
		top=$(cd $top/..; pwd)
		[[ $top == "/" ]] && return 1
	done
	echo "$top"
}

function git_uncommitted() {
	local changes=$(git status --porcelain 2>/dev/null | wc -l)
	[[ $changes -eq 0 ]] && return 1
	return 0
}

####
# main

# find the kernel top directory
top=$(kernel_top)
[[ -z $top ]] && exit_error "not in a kernel directory"
chkpatch="$top/scripts/checkpatch.pl"
dep_check git $chkpatch

# check for uncommitted changes
git_uncommitted && echo ">>> WARNING: you have uncommitted changes"

# run checkpatch on the top commit
git format-patch --stdout -1 | $chkpatch
